// Generated by CoffeeScript 1.6.2
(function() {
  var $, _ref;

  if ((_ref = window.YS) == null) {
    window.YS = {};
  }

  $ = window.jQuery;

  YS.BaseItem = Backbone.Model.extend({
    initialize: function() {}
  });

  YS.ItemListView = Backbone.View.extend({
    remove: function(i) {
      this.model.remove(this.model.at(i));
      this.render();
      return this;
    },
    update: function() {
      return this;
    },
    getTableHtml: function() {
      var getTbody, getThead, self, tbody, thead;

      self = this;
      getThead = function(fields) {
        var thead;

        thead = '<thead><tr>';
        _.each(fields, function(field) {
          return thead += "<th class='" + field.className + "'>" + field.name + "</th>";
        });
        return thead += '</tr></thead>';
      };
      getTbody = function(items) {
        var getTr, tbody;

        getTr = function(item) {
          return self.template(item);
        };
        tbody = '<tbody>';
        _.each(items, function(item, i) {
          if (i % 2) {
            item.className = 'odd';
          } else {
            item.className = 'even';
          }
          return tbody += getTr(item);
        });
        return tbody += '</tbody>';
      };
      thead = getThead(this.options.fields);
      tbody = getTbody(this.model.toJSON());
      return "<table>" + thead + tbody + "</table>";
    },
    async: function(data, i) {
      this.model.at(i).set(data);
      this.update();
      return this;
    }
  });

}).call(this);
