// Generated by CoffeeScript 1.6.2
(function() {
  var $, _ref;

  if ((_ref = window.YS) == null) {
    window.YS = {};
  }

  $ = window.jQuery;

  YS.SelectItem = YS.BaseItem.extend({});

  YS.SelectItemList = Backbone.Collection.extend({
    model: YS.SelectItem
  });

  YS.SelectItemListView = YS.ItemListView.extend({
    template: _.template('<tr class="item">' + '<td><a href="javascript:;" class="check"></a></td>' + '<td><%= name %></td>' + '<td><%= barcode %></td>' + '<td><%= size %></td>' + '</tr>'),
    events: {
      'click .select': 'select',
      'click .close': 'close',
      'dblclick .item': 'itemDblClick',
      'click .item': 'itemClick'
    },
    initialize: function() {
      this.$el.addClass('selectItemTable itemTable');
      return this.render();
    },
    itemDblClick: function(e) {
      var obj;

      obj = $(e.currentTarget);
      return this.getData([obj.index()]);
    },
    itemClick: function(e) {
      var obj;

      obj = $(e.currentTarget);
      return obj.find('.check').toggleClass('selected');
    },
    select: function(e) {
      var $el, indexArr;

      $el = this.$el;
      indexArr = [];
      $el.find('.item .check.selected').each(function() {
        var obj;

        obj = $(this);
        return indexArr.push(obj.closest('.item').index());
      });
      return this.getData(indexArr);
    },
    getData: function(indexArr) {
      var model, selectedData;

      model = this.model;
      selectedData = [];
      _.each(indexArr, function(index) {
        var item;

        item = model.at(index);
        if (item) {
          return selectedData.push(item.toJSON());
        }
      });
      this.options.select(selectedData);
      return this.close();
    },
    open: function(key) {
      return this.$el.show();
    },
    close: function() {
      return this.$el.hide().find('.item .check.selected').removeClass('selected');
    },
    render: function() {
      var ctrlsStr, self, tableHtml;

      self = this;
      tableHtml = this.getTableHtml();
      ctrlsStr = '<div class="ctrlBtns"><a class="select btn" href="javascript:;">确定</a><a class="close btn" href="javascript:;">关闭</a></div>';
      return this.$el.html("" + tableHtml + ctrlsStr);
    }
  });

}).call(this);
